### ISSUE TITLE
What is sig in Signature verification?

### ISSUE THREAD

**Issue by sadan-gamium** [getsafepay/safepay-python#7]
Hi

I am trying to implement Safepay on my website. I am able to successfully integrate the checkout flow but struggling with the verification of the signature.

- [ ] bug report
- [ ] feature request
- [x] question

## What is the current behavior?
N/A

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
N/A

## What is the expected behavior?
N/A

## What is the motivation / use case for changing the behavior?
I want to validate the tracker and I see in your docs that we can do this with [signature verification](https://github.com/getsafepay/safepay-python#signature) but I don't understand what does `sig` represent. I tried with both the API Key and Secret key provided at the time of account creation and I am getting negative result. 

## Please tell us about your environment:

Browser:

Environment:

- [ ] Production
- [x] Sandbox
- [ ] Development

**Comment by sadan-gamium** [comment]
I think I figured it out. Thanks

**Comment by hesham-04** [comment]
@sadan-gamium
Would it be possible for you to share the checkout flow source code with me, or maybe look into my my code?
it would really be of great help...
