### ISSUE TITLE
Event Loop Causing Problems 

### ISSUE THREAD

**Issue by hesham-04** [getsafepay/safepay-python#8]
## I'm submitting an Issue

- [x] bug report
- [ ] feature request

## What is the current behavior?

When attempting to call the `set_payment_details` method of the `Safepay` class in a Django view, I encounter the following error:

```
RuntimeError: There is no current event loop in thread 'Thread-5 (process_request_thread)'.
```

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

1. Create a Django view that calls the `set_payment_details` method of the `Safepay` class.
2. Inside the `set_payment_details` method, try to await an asynchronous payment function.
3. Run the view and observe the error message.

Here's a simplified code example demonstrating the issue:

```python
from django.http import JsonResponse
from django.views import View

class CreatePaymentView(View):
    def post(self, request, *args, **kwargs):
        payment_details = {
            "amount": 1000,
            "currency": "PKR",
            "description": "Test payment",
        }

        safepay = Safepay(settings.SAFEPAY_CONFIG)  # Ensure you have the correct config loaded

        try:
            payment_value = safepay.set_payment_details(payment_details)  # This line throws the error
        except Exception as e:
            return JsonResponse({'status': 'error', 'message': str(e)}, status=500)
```

## What is the expected behavior?

I expect the `set_payment_details` method to execute without throwing any runtime errors and allow for payment processing.

## What is the motivation / use case for changing the behavior?

This issue prevents the payment processing functionality from working correctly in my Django application, hindering transaction handling.

## Please tell us about your environment:

**Browser:** (e.g., Chrome, Firefox, etc.)

**Environment:**

- [ ] Production
- [x] Sandbox
- [ ] Development

---

**Comment by hesham-04** [comment]
@mrsaeeddev newbie here!

**Comment by hesham-04** [comment]
@fatimaaurangzeb0640 @mrsaeeddev 
Is this because of Django being multithreaded? 
Tried asyncio.run() in the Safepay class, didn't work either?

**Comment by hesham-04** [comment]
### Simple fix?

To handle this error, wrap the event loop handling with a `try-except` block:

```python
try:
    loop = asyncio.get_event_loop()
except RuntimeError as e:
    if str(e).startswith('There is no current event loop in thread'):
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
    else:
        raise

**Comment by mrsaeeddev** [comment]
Hey Hesham,

Thanks for raising the issue and suggesting the fix.

Yes, it occurs because the code is trying to run an async function in a thread that doesn't have an active event loop. It could happen (in the case of some web frameworks) where a thread is not available, or in cases when a thread doesn't have an event loop setup by default.

Your solution will work too, but you can also do something like this after you get current event loop from `asyncio`:

```
payment_value = loop.run_until_complete(paymentFunction(payment_details))
return payment_value
```

Furthermore, we will fix it on our end as well.

Let me know if you need any further help.

- Saeed

**Comment by hesham-04** [comment]
It's working as expected!
Thanks Saeed!
